apiVersion: v1
kind: Service
metadata:
  name: jabberwocky-server
spec:
  selector:
    app: jabberwocky
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: NodePort