apiVersion: apps/v1
kind: Deployment
metadata:
  name: jabberwocky-server
  labels:
    app: "jabberwocky"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: jabberwocky-server
      tier: backend
  template:
    metadata:
      labels:
        name: jabberwocky-server
        tier: backend
        app: "jabberwocky"
    spec:
      serviceAccountName: jabberwocky-server
      containers:
        - name: jabberwocky-server
          image: docker.io/squakez/jbw-server:0.0.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          command:
            - jabberwocky
